/**
 * Every product path as it was before the API moved under `/api/v1`, including the development
 * mail listing and the session-token alias. None is kept as an alias: each must answer 404.
 */
export const retiredApiPaths = [
  ["GET", "/api/approval-requests/:requestId"],
  ["GET", "/api/approval-requests"],
  ["GET", "/api/approval-requests/pending-count"],
  ["POST", "/api/approval-requests/:requestId/decide"],
  ["POST", "/api/approval-requests/:requestId/withdraw"],
  ["POST", "/api/approval-requests/:requestId/revert"],
  ["GET", "/api/me"],
  ["PATCH", "/api/me"],
  ["DELETE", "/api/me"],
  ["GET", "/api/me/model-preference"],
  ["PUT", "/api/me/model-preference"],
  ["POST", "/api/me/password"],
  ["POST", "/api/password-reset"],
  ["POST", "/api/password-setup"],
  ["GET", "/api/branding"],
  ["GET", "/api/config"],
  ["POST", "/api/collaboration-workspaces/personal"],
  ["GET", "/api/collaboration-workspaces"],
  ["POST", "/api/collaboration-workspaces"],
  ["GET", "/api/collaboration-workspaces/directory"],
  ["GET", "/api/collaboration-workspaces/:collaborationWorkspaceId"],
  ["PATCH", "/api/collaboration-workspaces/:collaborationWorkspaceId"],
  ["DELETE", "/api/collaboration-workspaces/:collaborationWorkspaceId"],
  ["GET", "/api/collaboration-workspaces/:collaborationWorkspaceId/agents"],
  ["GET", "/api/collaboration-workspaces/:collaborationWorkspaceId/deletion-impact"],
  ["GET", "/api/collaboration-workspaces/:collaborationWorkspaceId/members"],
  ["POST", "/api/collaboration-workspaces/:collaborationWorkspaceId/members"],
  ["GET", "/api/collaboration-workspaces/:collaborationWorkspaceId/member-candidates"],
  ["PATCH", "/api/collaboration-workspaces/:collaborationWorkspaceId/members/:userId"],
  ["DELETE", "/api/collaboration-workspaces/:collaborationWorkspaceId/members/:userId"],
  ["DELETE", "/api/collaboration-workspaces/:collaborationWorkspaceId/members/me"],
  ["POST", "/api/collaboration-workspaces/:collaborationWorkspaceId/access-requests"],
  ["GET", "/api/collaboration-workspaces/:collaborationWorkspaceId/access-requests"],
  [
    "POST",
    "/api/collaboration-workspaces/:collaborationWorkspaceId/access-requests/:userId/approve"
  ],
  ["DELETE", "/api/collaboration-workspaces/:collaborationWorkspaceId/access-requests/:userId"],
  ["GET", "/api/conversations"],
  ["POST", "/api/conversations"],
  ["POST", "/api/conversations/:conversationId/title"],
  ["PATCH", "/api/conversations/:conversationId/title"],
  ["POST", "/api/conversations/:conversationId/move"],
  ["GET", "/api/conversations/:conversationId/thread"],
  ["GET", "/api/conversations/:conversationId/messages"],
  ["GET", "/api/conversations/:conversationId/resources"],
  ["GET", "/api/conversations/:conversationId/structured-data/:structuredDataResourceId"],
  ["POST", "/api/conversations/:conversationId/runs/:runId/cancel"],
  ["POST", "/api/conversations/:conversationId/runs"],
  ["POST", "/api/conversations/runs"],
  ["GET", "/api/conversations/:conversationId/runs/:runId/events"],
  ["POST", "/api/conversations/:conversationId/runs/:runId/commands"],
  ["DELETE", "/api/conversations/:conversationId"],
  ["POST", "/api/conversations/:conversationId/artifacts/:artifactId/preview"],
  ["GET", "/api/conversations/:conversationId/artifacts/:artifactId/preview"],
  ["POST", "/api/conversations/:conversationId/attachments/:attachmentId/preview"],
  ["GET", "/api/conversations/:conversationId/attachments/:attachmentId/preview"],
  ["GET", "/api/conversations/:conversationId/draft-attachments"],
  ["POST", "/api/conversations/:conversationId/draft-attachments"],
  ["POST", "/api/conversations/:conversationId/draft-attachments/:attachmentId/retry"],
  ["DELETE", "/api/conversations/:conversationId/draft-attachments/:attachmentId"],
  ["GET", "/api/conversations/:conversationId/files/:fileId/content"],
  ["GET", "/api/conversations/:conversationId/artifacts/:artifactId/content"],
  ["POST", "/api/conversations/:conversationId/artifacts/:artifactId/preview/retry"],
  ["GET", "/api/audit-events"],
  ["GET", "/api/audit-activities"],
  ["GET", "/api/superadmin/usage"],
  ["GET", "/api/admin/config/assets"],
  ["GET", "/api/admin/config/assets/:kind/:name"],
  ["PUT", "/api/admin/config/assets/:kind/:name"],
  ["POST", "/api/admin/config/assets/:kind/:name/delete"],
  ["PUT", "/api/admin/config/default-agent"],
  ["PUT", "/api/admin/config/agents/:name/availability"],
  ["GET", "/api/admin/collaboration-workspaces"],
  ["GET", "/api/admin/config/assets/:kind/:name/revisions"],
  ["POST", "/api/admin/config/assets/:kind/:name/revert"],
  ["GET", "/api/admin/config/export"],
  ["POST", "/api/admin/config/import"],
  ["POST", "/api/admin/config/validate"],
  ["GET", "/api/superadmin/users"],
  ["POST", "/api/superadmin/users"],
  ["PATCH", "/api/superadmin/users/:userId"],
  ["DELETE", "/api/superadmin/users/:userId"],
  ["PUT", "/api/superadmin/users/:userId/identities"],
  ["POST", "/api/superadmin/users/:userId/password"],
  ["POST", "/api/superadmin/users/:userId/invitation"],
  ["DELETE", "/api/superadmin/users/:userId/identities/:authSource/:externalUserId"],
  ["GET", "/api/superadmin/api-access/service-principals"],
  ["POST", "/api/superadmin/api-access/service-principals"],
  ["PATCH", "/api/superadmin/api-access/service-principals/:servicePrincipalId"],
  ["POST", "/api/superadmin/api-access/service-principals/:servicePrincipalId/credentials"],
  ["POST", "/api/superadmin/api-access/credentials/:credentialId/revoke"],
  ["POST", "/api/superadmin/session-tokens"],
  ["POST", "/api/auth/access-token"],
  ["GET", "/api/dev/captured-mail"],
  ["POST", "/auth/session-token"]
] as const satisfies readonly (readonly ["GET" | "POST" | "PATCH" | "PUT" | "DELETE", string])[];

/**
 * The asset addresses of the release before `/api/v1/assets`, with an agent named. None is
 * kept as an alias: each must answer 404.
 */
export const removedAssetPaths = [
  ["GET", "/api/v1/instance/config/assets/agent/assistant"],
  ["PUT", "/api/v1/instance/config/assets/agent/assistant"],
  ["POST", "/api/v1/instance/config/assets/agent/assistant/delete"],
  ["POST", "/api/v1/instance/config/assets/agent/assistant/revert"],
  ["GET", "/api/v1/instance/config/assets/agent/assistant/revisions"]
] as const satisfies readonly (readonly ["GET" | "POST" | "PUT", string])[];
