export const CLIENT_INSTANCE_ENV_NAMES = {
  HOST: "HOST",
  PORT: "PORT",
  CLIENT_CONFIG_PATH: "CLIENT_CONFIG_PATH",
  BETTER_AUTH_URL: "BETTER_AUTH_URL",
  CHAT_UI_ORIGIN: "CHAT_UI_ORIGIN",
  AGENT_RUN_WORKER_ID: "AGENT_RUN_WORKER_ID",
  AGENT_RUN_WORKER_CONCURRENCY: "AGENT_RUN_WORKER_CONCURRENCY",
  AGENT_RUN_WORKER_DRAIN_TIMEOUT_MS: "AGENT_RUN_WORKER_DRAIN_TIMEOUT_MS",
  WORKSPACE_COMMAND_TEMP_ROOT: "WORKSPACE_COMMAND_TEMP_ROOT",
  WORKSPACE_COMMAND_WORKER_ID: "WORKSPACE_COMMAND_WORKER_ID",
  EXECUTION_WORKSPACE_RUNNER_IMAGE: "EXECUTION_WORKSPACE_RUNNER_IMAGE",
  ARTIFACT_PREVIEW_WORKER_ID: "ARTIFACT_PREVIEW_WORKER_ID",
  ARTIFACT_PREVIEW_SOFFICE_COMMAND: "ARTIFACT_PREVIEW_SOFFICE_COMMAND",
  ARTIFACT_PREVIEW_PDFINFO_COMMAND: "ARTIFACT_PREVIEW_PDFINFO_COMMAND",
  ARTIFACT_PREVIEW_PDFTOPPM_COMMAND: "ARTIFACT_PREVIEW_PDFTOPPM_COMMAND",
  ARTIFACT_PREVIEW_TEMP_ROOT: "ARTIFACT_PREVIEW_TEMP_ROOT",
  ARTIFACT_PREVIEW_CONCURRENCY: "ARTIFACT_PREVIEW_CONCURRENCY",
  ARTIFACT_PREVIEW_MAX_PAGES: "ARTIFACT_PREVIEW_MAX_PAGES",
  ARTIFACT_PREVIEW_MAX_SOURCE_BYTES: "ARTIFACT_PREVIEW_MAX_SOURCE_BYTES",
  ARTIFACT_PREVIEW_MAX_CONVERTED_PDF_BYTES: "ARTIFACT_PREVIEW_MAX_CONVERTED_PDF_BYTES",
  ARTIFACT_PREVIEW_MAX_OUTPUT_BYTES: "ARTIFACT_PREVIEW_MAX_OUTPUT_BYTES",
  ARTIFACT_PREVIEW_MAX_RASTER_DIMENSION: "ARTIFACT_PREVIEW_MAX_RASTER_DIMENSION",
  ARTIFACT_PREVIEW_CONVERSION_TIMEOUT_MS: "ARTIFACT_PREVIEW_CONVERSION_TIMEOUT_MS",
  ARTIFACT_PREVIEW_RASTERIZATION_TIMEOUT_MS: "ARTIFACT_PREVIEW_RASTERIZATION_TIMEOUT_MS",
  ARTIFACT_PREVIEW_DPI: "ARTIFACT_PREVIEW_DPI"
} as const;

export type ClientInstanceEnv = Record<string, string | undefined>;

// Configured email names and secret-provider names are dynamic. Preserve the full map for
// those readers and dotenv loading, including the identity of a caller-supplied map.
export function readClientInstanceEnv(env?: ClientInstanceEnv): ClientInstanceEnv {
  return env ?? process.env;
}
