import { listQuerySchema } from "../shared";
import {
  createNamespaceRequestSchema,
  createPermissionGrantRequestSchema,
  effectivePermissionsQuerySchema,
  effectivePermissionsSchema,
  listPermissionGrantsQuerySchema,
  namespaceSchema,
  namespaceUsageSchema,
  permissionGrantSchema,
  updateNamespaceRequestSchema
} from "../access";
import { defineOperation, json, page } from "./define-operation";

export const accessOperations = {
  "permissions.grant": defineOperation({
    id: "permissions.grant",
    method: "POST",
    path: "/api/v1/instance/access/grants",
    summary: "Allow or deny a user an action in a Namespace or on one asset",
    tag: "Access",
    auth: "user",
    scope: "user_admin:write",
    requires: ["users.manage"],
    effect: "changing",
    body: createPermissionGrantRequestSchema,
    response: json(permissionGrantSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  "permissions.revoke": defineOperation({
    id: "permissions.revoke",
    method: "DELETE",
    path: "/api/v1/instance/access/grants/:grantId",
    summary: "Remove a grant row",
    tag: "Access",
    auth: "user",
    scope: "user_admin:write",
    requires: ["users.manage"],
    effect: "changing",
    response: json(permissionGrantSchema),
    errors: ["NOT_FOUND"],
    rateClass: "write"
  }),
  "permissions.list": defineOperation({
    id: "permissions.list",
    method: "GET",
    path: "/api/v1/instance/access/grants",
    summary: "List grant rows",
    tag: "Access",
    auth: "user",
    scope: "user_admin:read",
    requires: ["users.manage"],
    effect: "reading",
    query: listPermissionGrantsQuerySchema,
    response: page(permissionGrantSchema, ["holderId", "id"], false),
    errors: [],
    rateClass: "read"
  }),
  "permissions.effective": defineOperation({
    id: "permissions.effective",
    method: "GET",
    path: "/api/v1/instance/access/effective",
    summary: "List what one holder is allowed and denied, with the source of each entry",
    tag: "Access",
    auth: "user",
    scope: "user_admin:read",
    requires: ["users.manage"],
    effect: "reading",
    query: effectivePermissionsQuerySchema,
    response: json(effectivePermissionsSchema),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  "namespaces.create": defineOperation({
    id: "namespaces.create",
    method: "POST",
    path: "/api/v1/instance/access/namespaces",
    summary: "Register a name prefix as a Namespace",
    tag: "Access",
    auth: "user",
    scope: "user_admin:write",
    requires: ["users.manage"],
    effect: "changing",
    body: createNamespaceRequestSchema,
    response: json(namespaceSchema),
    errors: ["CONFLICT"],
    rateClass: "write"
  }),
  "namespaces.update": defineOperation({
    id: "namespaces.update",
    method: "PATCH",
    path: "/api/v1/instance/access/namespaces/:prefix",
    summary: "Change a Namespace's display name and its tool and model lists",
    tag: "Access",
    auth: "user",
    scope: "user_admin:write",
    requires: ["users.manage"],
    effect: "changing",
    body: updateNamespaceRequestSchema,
    response: json(namespaceSchema),
    errors: ["NOT_FOUND"],
    rateClass: "write"
  }),
  "namespaces.list": defineOperation({
    id: "namespaces.list",
    method: "GET",
    path: "/api/v1/instance/access/namespaces",
    summary: "List Namespaces with the grants and assets each one covers",
    tag: "Access",
    auth: "user",
    scope: "user_admin:read",
    requires: ["users.manage"],
    effect: "reading",
    query: listQuerySchema,
    response: page(namespaceUsageSchema, ["prefix"], false),
    errors: [],
    rateClass: "read"
  }),
  "namespaces.delete": defineOperation({
    id: "namespaces.delete",
    method: "DELETE",
    path: "/api/v1/instance/access/namespaces/:prefix",
    summary: "Delete a Namespace that no grant row names",
    tag: "Access",
    auth: "user",
    scope: "user_admin:write",
    requires: ["users.manage"],
    effect: "changing",
    response: json(namespaceSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  })
} as const;
