import { z } from "zod";
import {
  addWorkspaceMemberRequestSchema,
  collaborationWorkspaceDeletionImpactSchema,
  collaborationWorkspaceDeletionResultSchema,
  collaborationWorkspaceDirectoryItemSchema,
  collaborationWorkspaceWithRoleSchema,
  createCollaborationWorkspaceRequestSchema,
  deleteCollaborationWorkspaceRequestSchema,
  updateCollaborationWorkspaceRequestSchema,
  updateWorkspaceMemberRoleRequestSchema,
  workspaceAccessRequestItemSchema,
  workspaceAccessRequestSchema,
  workspaceMemberCandidateSchema,
  workspaceMemberSchema,
  workspaceMembershipSchema
} from "../collaboration-workspaces";
import { collaborationWorkspaceAgentsSchema } from "../configuration";
import { defineOperation, json } from "./define-operation";

export const collaborationWorkspaceOperations = {
  listCollaborationWorkspaces: defineOperation({
    id: "listCollaborationWorkspaces",
    method: "GET",
    path: "/api/collaboration-workspaces",
    summary: "List the workspaces the caller belongs to",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:read",
    requires: [],
    effect: "reading",
    response: json(z.array(collaborationWorkspaceWithRoleSchema)),
    errors: [],
    rateClass: "read"
  }),
  createCollaborationWorkspace: defineOperation({
    id: "createCollaborationWorkspace",
    method: "POST",
    path: "/api/collaboration-workspaces",
    summary: "Create a Shared Workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    body: createCollaborationWorkspaceRequestSchema,
    response: json(collaborationWorkspaceWithRoleSchema),
    errors: ["CONFLICT"],
    rateClass: "write"
  }),
  listCollaborationWorkspaceDirectory: defineOperation({
    id: "listCollaborationWorkspaceDirectory",
    method: "GET",
    path: "/api/collaboration-workspaces/directory",
    summary: "List the Shared Workspaces a member can find",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:read",
    requires: [],
    effect: "reading",
    response: json(z.array(collaborationWorkspaceDirectoryItemSchema)),
    errors: [],
    rateClass: "read"
  }),
  getCollaborationWorkspace: defineOperation({
    id: "getCollaborationWorkspace",
    method: "GET",
    path: "/api/collaboration-workspaces/:collaborationWorkspaceId",
    summary: "Read one workspace with the caller's role",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:read",
    requires: [],
    effect: "reading",
    response: json(collaborationWorkspaceWithRoleSchema),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  listCollaborationWorkspaceAgents: defineOperation({
    id: "listCollaborationWorkspaceAgents",
    method: "GET",
    path: "/api/collaboration-workspaces/:collaborationWorkspaceId/agents",
    summary: "List the agents available in a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "config:read",
    requires: [],
    effect: "reading",
    query: z.object({ locale: z.string().optional() }),
    response: json(collaborationWorkspaceAgentsSchema),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  updateCollaborationWorkspace: defineOperation({
    id: "updateCollaborationWorkspace",
    method: "PATCH",
    path: "/api/collaboration-workspaces/:collaborationWorkspaceId",
    summary: "Change a workspace's settings",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    body: updateCollaborationWorkspaceRequestSchema,
    response: json(collaborationWorkspaceWithRoleSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  getCollaborationWorkspaceDeletionImpact: defineOperation({
    id: "getCollaborationWorkspaceDeletionImpact",
    method: "GET",
    path: "/api/collaboration-workspaces/:collaborationWorkspaceId/deletion-impact",
    summary: "Read what deleting a Shared Workspace would remove",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "reading",
    response: json(collaborationWorkspaceDeletionImpactSchema),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  deleteCollaborationWorkspace: defineOperation({
    id: "deleteCollaborationWorkspace",
    method: "DELETE",
    path: "/api/collaboration-workspaces/:collaborationWorkspaceId",
    summary: "Delete a Shared Workspace and its conversations",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    body: deleteCollaborationWorkspaceRequestSchema,
    response: json(collaborationWorkspaceDeletionResultSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  listCollaborationWorkspaceMembers: defineOperation({
    id: "listCollaborationWorkspaceMembers",
    method: "GET",
    path: "/api/collaboration-workspaces/:collaborationWorkspaceId/members",
    summary: "List the members of a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:read",
    requires: [],
    effect: "reading",
    response: json(z.array(workspaceMemberSchema)),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  listCollaborationWorkspaceMemberCandidates: defineOperation({
    id: "listCollaborationWorkspaceMemberCandidates",
    method: "GET",
    path: "/api/collaboration-workspaces/:collaborationWorkspaceId/member-candidates",
    summary: "Search users who can be added to a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "reading",
    query: z.object({ q: z.string().optional() }),
    response: json(z.array(workspaceMemberCandidateSchema)),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  addCollaborationWorkspaceMember: defineOperation({
    id: "addCollaborationWorkspaceMember",
    method: "POST",
    path: "/api/collaboration-workspaces/:collaborationWorkspaceId/members",
    summary: "Add a user to a workspace by email",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    body: addWorkspaceMemberRequestSchema,
    response: json(workspaceMemberSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  updateCollaborationWorkspaceMemberRole: defineOperation({
    id: "updateCollaborationWorkspaceMemberRole",
    method: "PATCH",
    path: "/api/collaboration-workspaces/:collaborationWorkspaceId/members/:userId",
    summary: "Change a member's role in a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    body: updateWorkspaceMemberRoleRequestSchema,
    response: json(workspaceMembershipSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  removeCollaborationWorkspaceMember: defineOperation({
    id: "removeCollaborationWorkspaceMember",
    method: "DELETE",
    path: "/api/collaboration-workspaces/:collaborationWorkspaceId/members/:userId",
    summary: "Remove a member from a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    response: json(workspaceMembershipSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  leaveCollaborationWorkspace: defineOperation({
    id: "leaveCollaborationWorkspace",
    method: "DELETE",
    path: "/api/collaboration-workspaces/:collaborationWorkspaceId/members/me",
    summary: "Leave a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    response: json(workspaceMembershipSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  requestCollaborationWorkspaceAccess: defineOperation({
    id: "requestCollaborationWorkspaceAccess",
    method: "POST",
    path: "/api/collaboration-workspaces/:collaborationWorkspaceId/access-requests",
    summary: "Ask to join a Shared Workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    response: json(workspaceAccessRequestSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  listCollaborationWorkspaceAccessRequests: defineOperation({
    id: "listCollaborationWorkspaceAccessRequests",
    method: "GET",
    path: "/api/collaboration-workspaces/:collaborationWorkspaceId/access-requests",
    summary: "List the open requests to join a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:read",
    requires: [],
    effect: "reading",
    response: json(z.array(workspaceAccessRequestItemSchema)),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  approveCollaborationWorkspaceAccessRequest: defineOperation({
    id: "approveCollaborationWorkspaceAccessRequest",
    method: "POST",
    path: "/api/collaboration-workspaces/:collaborationWorkspaceId/access-requests/:userId/approve",
    summary: "Approve a request to join a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    response: json(workspaceMembershipSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  declineCollaborationWorkspaceAccessRequest: defineOperation({
    id: "declineCollaborationWorkspaceAccessRequest",
    method: "DELETE",
    path: "/api/collaboration-workspaces/:collaborationWorkspaceId/access-requests/:userId",
    summary: "Decline a request to join a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    response: json(workspaceAccessRequestSchema),
    errors: ["NOT_FOUND"],
    rateClass: "write"
  })
} as const;
