import { listQuerySchema } from "../shared";
import { z } from "zod";
import {
  addWorkspaceMemberRequestSchema,
  collaborationWorkspaceDeletionImpactSchema,
  collaborationWorkspaceDeletionResultSchema,
  collaborationWorkspaceDirectoryItemSchema,
  collaborationWorkspaceWithRoleSchema,
  createCollaborationWorkspaceRequestSchema,
  deleteCollaborationWorkspaceRequestSchema,
  updateCollaborationWorkspaceRequestSchema,
  updateWorkspaceMemberRoleRequestSchema,
  workspaceAccessRequestItemSchema,
  workspaceAccessRequestSchema,
  workspaceMemberCandidateSchema,
  workspaceMemberSchema,
  workspaceMembershipSchema
} from "../collaboration-workspaces";
import { collaborationWorkspaceAgentsSchema } from "../configuration";
import { defineOperation, json, page } from "./define-operation";

export const collaborationWorkspaceOperations = {
  "workspaces.ensure_personal": defineOperation({
    id: "workspaces.ensure_personal",
    method: "POST",
    path: "/api/v1/workspaces/personal",
    summary: "Create the caller's personal workspace if missing",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:read",
    requires: [],
    effect: "changing",
    response: json(collaborationWorkspaceWithRoleSchema),
    errors: [],
    rateClass: "write"
  }),
  "workspaces.list": defineOperation({
    id: "workspaces.list",
    method: "GET",
    path: "/api/v1/workspaces",
    summary: "List the workspaces the caller belongs to",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:read",
    requires: [],
    effect: "reading",
    query: listQuerySchema,
    response: page(collaborationWorkspaceWithRoleSchema, ["createdAt", "id"], false),
    errors: [],
    rateClass: "read"
  }),
  "workspaces.create": defineOperation({
    id: "workspaces.create",
    method: "POST",
    path: "/api/v1/workspaces",
    summary: "Create a Shared Workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    body: createCollaborationWorkspaceRequestSchema,
    response: json(collaborationWorkspaceWithRoleSchema),
    errors: ["CONFLICT"],
    rateClass: "write"
  }),
  "workspaces.directory.list": defineOperation({
    id: "workspaces.directory.list",
    method: "GET",
    path: "/api/v1/workspaces/directory",
    summary: "List the Shared Workspaces a member can find",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:read",
    requires: [],
    effect: "reading",
    query: listQuerySchema,
    response: page(collaborationWorkspaceDirectoryItemSchema, ["createdAt", "id"], false),
    errors: [],
    rateClass: "read"
  }),
  "workspaces.get": defineOperation({
    id: "workspaces.get",
    method: "GET",
    path: "/api/v1/workspaces/:collaborationWorkspaceId",
    summary: "Read one workspace with the caller's role",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:read",
    requires: [],
    effect: "reading",
    response: json(collaborationWorkspaceWithRoleSchema),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  "workspaces.agents.list": defineOperation({
    id: "workspaces.agents.list",
    method: "GET",
    path: "/api/v1/workspaces/:collaborationWorkspaceId/agents",
    summary: "List the agents available in a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "config:read",
    requires: [],
    effect: "reading",
    query: listQuerySchema.extend({ locale: z.string().optional() }),
    response: json(collaborationWorkspaceAgentsSchema),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  "workspaces.update": defineOperation({
    id: "workspaces.update",
    method: "PATCH",
    path: "/api/v1/workspaces/:collaborationWorkspaceId",
    summary: "Change a workspace's settings",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    body: updateCollaborationWorkspaceRequestSchema,
    response: json(collaborationWorkspaceWithRoleSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  "workspaces.deletion_impact.get": defineOperation({
    id: "workspaces.deletion_impact.get",
    method: "GET",
    path: "/api/v1/workspaces/:collaborationWorkspaceId/deletion-impact",
    summary: "Read what deleting a Shared Workspace would remove",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "reading",
    response: json(collaborationWorkspaceDeletionImpactSchema),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  "workspaces.delete": defineOperation({
    id: "workspaces.delete",
    method: "DELETE",
    path: "/api/v1/workspaces/:collaborationWorkspaceId",
    summary: "Delete a Shared Workspace and its conversations",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    body: deleteCollaborationWorkspaceRequestSchema,
    response: json(collaborationWorkspaceDeletionResultSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  "workspaces.members.list": defineOperation({
    id: "workspaces.members.list",
    method: "GET",
    path: "/api/v1/workspaces/:collaborationWorkspaceId/members",
    summary: "List the members of a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:read",
    requires: [],
    effect: "reading",
    query: listQuerySchema,
    response: page(workspaceMemberSchema, ["displayLabel", "userId"], false),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  "workspaces.member_candidates.list": defineOperation({
    id: "workspaces.member_candidates.list",
    method: "GET",
    path: "/api/v1/workspaces/:collaborationWorkspaceId/member-candidates",
    summary: "Search users who can be added to a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "reading",
    query: listQuerySchema.extend({ q: z.string().optional() }),
    response: page(workspaceMemberCandidateSchema, ["displayLabel", "email", "userId"], false),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  "workspaces.members.add": defineOperation({
    id: "workspaces.members.add",
    method: "POST",
    path: "/api/v1/workspaces/:collaborationWorkspaceId/members",
    summary: "Add a user to a workspace by email",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    body: addWorkspaceMemberRequestSchema,
    response: json(workspaceMemberSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  "workspaces.members.update_role": defineOperation({
    id: "workspaces.members.update_role",
    method: "PATCH",
    path: "/api/v1/workspaces/:collaborationWorkspaceId/members/:userId",
    summary: "Change a member's role in a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    body: updateWorkspaceMemberRoleRequestSchema,
    response: json(workspaceMembershipSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  "workspaces.members.remove": defineOperation({
    id: "workspaces.members.remove",
    method: "DELETE",
    path: "/api/v1/workspaces/:collaborationWorkspaceId/members/:userId",
    summary: "Remove a member from a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    response: json(workspaceMembershipSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  "workspaces.members.leave": defineOperation({
    id: "workspaces.members.leave",
    method: "DELETE",
    path: "/api/v1/workspaces/:collaborationWorkspaceId/members/me",
    summary: "Leave a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    response: json(workspaceMembershipSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  "workspaces.access_requests.create": defineOperation({
    id: "workspaces.access_requests.create",
    method: "POST",
    path: "/api/v1/workspaces/:collaborationWorkspaceId/access-requests",
    summary: "Ask to join a Shared Workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    response: json(workspaceAccessRequestSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  "workspaces.access_requests.list": defineOperation({
    id: "workspaces.access_requests.list",
    method: "GET",
    path: "/api/v1/workspaces/:collaborationWorkspaceId/access-requests",
    summary: "List the open requests to join a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:read",
    requires: [],
    effect: "reading",
    query: listQuerySchema,
    response: page(workspaceAccessRequestItemSchema, ["createdAt", "userId"], false),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  "workspaces.access_requests.approve": defineOperation({
    id: "workspaces.access_requests.approve",
    method: "POST",
    path: "/api/v1/workspaces/:collaborationWorkspaceId/access-requests/:userId/approve",
    summary: "Approve a request to join a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    response: json(workspaceMembershipSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  "workspaces.access_requests.decline": defineOperation({
    id: "workspaces.access_requests.decline",
    method: "DELETE",
    path: "/api/v1/workspaces/:collaborationWorkspaceId/access-requests/:userId",
    summary: "Decline a request to join a workspace",
    tag: "Collaboration Workspaces",
    auth: "user",
    scope: "collaboration_workspace:manage",
    requires: [],
    effect: "changing",
    response: json(workspaceAccessRequestSchema),
    errors: ["NOT_FOUND"],
    rateClass: "write"
  })
} as const;
