import { listQuerySchema } from "../shared";
import {
  administeredCollaborationWorkspaceSchema,
  agentAvailabilitySchema,
  configAssetBundleSchema,
  configAssetMutationVersionRequestSchema,
  configAssetMutationVersionResponseSchema,
  configAssetRevisionSchema,
  configAssetSchema,
  configAssetsOverviewSchema,
  exportConfigAssetsResponseSchema,
  putConfigAssetRequestSchema,
  putConfigAssetResponseSchema,
  replaceConfigAssetsRequestSchema,
  replaceConfigAssetsResponseSchema,
  revertConfigAssetRequestSchema,
  setConfigAgentAvailabilityRequestSchema,
  setDefaultConfigAgentRequestSchema,
  validateConfigAssetsResponseSchema
} from "../configuration";
import { defineOperation, json, page } from "./define-operation";

export const configAssetOperations = {
  "config_assets.get_overview": defineOperation({
    id: "config_assets.get_overview",
    method: "GET",
    path: "/api/v1/instance/config/assets",
    summary: "List agents and skills with their revisions",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:read",
    requires: ["agent.read", "skill.read"],
    effect: "reading",
    response: json(configAssetsOverviewSchema),
    errors: [],
    rateClass: "read"
  }),
  "config_assets.get": defineOperation({
    id: "config_assets.get",
    method: "GET",
    path: "/api/v1/instance/config/assets/:kind/:name",
    summary: "Read one agent or skill",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:read",
    requires: [],
    effect: "reading",
    response: json(configAssetSchema),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  "config_assets.put": defineOperation({
    id: "config_assets.put",
    method: "PUT",
    path: "/api/v1/instance/config/assets/:kind/:name",
    summary: "Create or replace one agent or skill",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:write",
    requires: [],
    effect: "changing",
    body: putConfigAssetRequestSchema,
    response: json(putConfigAssetResponseSchema),
    errors: ["CONFLICT"],
    rateClass: "write"
  }),
  "config_assets.delete": defineOperation({
    id: "config_assets.delete",
    method: "POST",
    path: "/api/v1/instance/config/assets/:kind/:name/delete",
    summary: "Delete one agent or skill",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:write",
    requires: [],
    effect: "changing",
    body: configAssetMutationVersionRequestSchema,
    response: json(configAssetMutationVersionResponseSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  "config_agents.set_default": defineOperation({
    id: "config_agents.set_default",
    method: "PUT",
    path: "/api/v1/instance/config/default-agent",
    summary: "Set or clear the default agent",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:write",
    requires: ["agent.write"],
    effect: "changing",
    body: setDefaultConfigAgentRequestSchema,
    response: json(configAssetMutationVersionResponseSchema),
    errors: ["CONFLICT"],
    rateClass: "write"
  }),
  "config_agents.set_availability": defineOperation({
    id: "config_agents.set_availability",
    method: "PUT",
    path: "/api/v1/instance/config/agents/:name/availability",
    summary: "Set the workspaces an agent is available in",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:write",
    requires: ["agent.write"],
    effect: "changing",
    body: setConfigAgentAvailabilityRequestSchema,
    response: json(agentAvailabilitySchema),
    errors: [],
    rateClass: "write"
  }),
  "instance.workspaces.list": defineOperation({
    id: "instance.workspaces.list",
    method: "GET",
    path: "/api/v1/instance/workspaces",
    summary: "List the Shared Workspaces an agent can be made available in",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:write",
    requires: ["agent.write"],
    effect: "reading",
    query: listQuerySchema,
    response: page(administeredCollaborationWorkspaceSchema, ["createdAt", "id"], false),
    errors: [],
    rateClass: "read"
  }),
  "config_assets.revisions.list": defineOperation({
    id: "config_assets.revisions.list",
    method: "GET",
    path: "/api/v1/instance/config/assets/:kind/:name/revisions",
    summary: "List the revisions of one agent or skill",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:read",
    requires: [],
    effect: "reading",
    query: listQuerySchema,
    response: page(configAssetRevisionSchema, ["revision"], false),
    errors: [],
    rateClass: "read"
  }),
  "config_assets.revert": defineOperation({
    id: "config_assets.revert",
    method: "POST",
    path: "/api/v1/instance/config/assets/:kind/:name/revert",
    summary: "Restore an earlier revision of one agent or skill",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:write",
    requires: [],
    effect: "changing",
    body: revertConfigAssetRequestSchema,
    response: json(putConfigAssetResponseSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  "config_assets.export": defineOperation({
    id: "config_assets.export",
    method: "GET",
    path: "/api/v1/instance/config/export",
    summary: "Export every agent and skill as one bundle",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:read",
    requires: ["agent.read", "skill.read"],
    effect: "reading",
    response: json(exportConfigAssetsResponseSchema),
    errors: [],
    rateClass: "read"
  }),
  "config_assets.replace": defineOperation({
    id: "config_assets.replace",
    method: "POST",
    path: "/api/v1/instance/config/import",
    summary: "Apply a bundle of agents and skills from a release",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:release",
    requires: ["assets.release"],
    effect: "changing",
    body: replaceConfigAssetsRequestSchema,
    response: json(replaceConfigAssetsResponseSchema),
    errors: ["CONFLICT"],
    rateClass: "write"
  }),
  "config_assets.validate": defineOperation({
    id: "config_assets.validate",
    method: "POST",
    path: "/api/v1/instance/config/validate",
    summary: "Check a bundle of agents and skills without applying it",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:release",
    requires: ["assets.release"],
    effect: "reading",
    body: configAssetBundleSchema,
    response: json(validateConfigAssetsResponseSchema),
    errors: [],
    rateClass: "read"
  })
} as const;
