import { z } from "zod";
import {
  administeredCollaborationWorkspaceSchema,
  agentAvailabilitySchema,
  configAssetBundleSchema,
  configAssetMutationVersionRequestSchema,
  configAssetMutationVersionResponseSchema,
  configAssetRevisionSchema,
  configAssetSchema,
  configAssetsOverviewSchema,
  exportConfigAssetsResponseSchema,
  putConfigAssetRequestSchema,
  putConfigAssetResponseSchema,
  replaceConfigAssetsRequestSchema,
  replaceConfigAssetsResponseSchema,
  revertConfigAssetRequestSchema,
  setConfigAgentAvailabilityRequestSchema,
  setDefaultConfigAgentRequestSchema,
  validateConfigAssetsResponseSchema
} from "../configuration";
import { defineOperation, json } from "./define-operation";

export const configAssetOperations = {
  getConfigAssetsOverview: defineOperation({
    id: "getConfigAssetsOverview",
    method: "GET",
    path: "/api/admin/config/assets",
    summary: "List agents and skills with their revisions",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:read",
    requires: ["agent.read", "skill.read"],
    effect: "reading",
    response: json(configAssetsOverviewSchema),
    errors: [],
    rateClass: "read"
  }),
  getConfigAsset: defineOperation({
    id: "getConfigAsset",
    method: "GET",
    path: "/api/admin/config/assets/:kind/:name",
    summary: "Read one agent or skill",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:read",
    requires: [],
    effect: "reading",
    response: json(configAssetSchema),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  putConfigAsset: defineOperation({
    id: "putConfigAsset",
    method: "PUT",
    path: "/api/admin/config/assets/:kind/:name",
    summary: "Create or replace one agent or skill",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:write",
    requires: [],
    effect: "changing",
    body: putConfigAssetRequestSchema,
    response: json(putConfigAssetResponseSchema),
    errors: ["CONFLICT"],
    rateClass: "write"
  }),
  deleteConfigAsset: defineOperation({
    id: "deleteConfigAsset",
    method: "POST",
    path: "/api/admin/config/assets/:kind/:name/delete",
    summary: "Delete one agent or skill",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:write",
    requires: [],
    effect: "changing",
    body: configAssetMutationVersionRequestSchema,
    response: json(configAssetMutationVersionResponseSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  setDefaultConfigAgent: defineOperation({
    id: "setDefaultConfigAgent",
    method: "PUT",
    path: "/api/admin/config/default-agent",
    summary: "Set or clear the default agent",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:write",
    requires: ["agent.write"],
    effect: "changing",
    body: setDefaultConfigAgentRequestSchema,
    response: json(configAssetMutationVersionResponseSchema),
    errors: ["CONFLICT"],
    rateClass: "write"
  }),
  setConfigAgentAvailability: defineOperation({
    id: "setConfigAgentAvailability",
    method: "PUT",
    path: "/api/admin/config/agents/:name/availability",
    summary: "Set the workspaces an agent is available in",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:write",
    requires: ["agent.write"],
    effect: "changing",
    body: setConfigAgentAvailabilityRequestSchema,
    response: json(agentAvailabilitySchema),
    errors: [],
    rateClass: "write"
  }),
  listAdministeredCollaborationWorkspaces: defineOperation({
    id: "listAdministeredCollaborationWorkspaces",
    method: "GET",
    path: "/api/admin/collaboration-workspaces",
    summary: "List the Shared Workspaces an agent can be made available in",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:write",
    requires: ["agent.write"],
    effect: "reading",
    response: json(z.array(administeredCollaborationWorkspaceSchema)),
    errors: [],
    rateClass: "read"
  }),
  listConfigAssetRevisions: defineOperation({
    id: "listConfigAssetRevisions",
    method: "GET",
    path: "/api/admin/config/assets/:kind/:name/revisions",
    summary: "List the revisions of one agent or skill",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:read",
    requires: [],
    effect: "reading",
    response: json(z.array(configAssetRevisionSchema)),
    errors: [],
    rateClass: "read"
  }),
  revertConfigAsset: defineOperation({
    id: "revertConfigAsset",
    method: "POST",
    path: "/api/admin/config/assets/:kind/:name/revert",
    summary: "Restore an earlier revision of one agent or skill",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:write",
    requires: [],
    effect: "changing",
    body: revertConfigAssetRequestSchema,
    response: json(putConfigAssetResponseSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  exportConfigAssets: defineOperation({
    id: "exportConfigAssets",
    method: "GET",
    path: "/api/admin/config/export",
    summary: "Export every agent and skill as one bundle",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:read",
    requires: ["agent.read", "skill.read"],
    effect: "reading",
    response: json(exportConfigAssetsResponseSchema),
    errors: [],
    rateClass: "read"
  }),
  replaceConfigAssets: defineOperation({
    id: "replaceConfigAssets",
    method: "POST",
    path: "/api/admin/config/import",
    summary: "Apply a bundle of agents and skills from a release",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:release",
    requires: ["assets.release"],
    effect: "changing",
    body: replaceConfigAssetsRequestSchema,
    response: json(replaceConfigAssetsResponseSchema),
    errors: ["CONFLICT"],
    rateClass: "write"
  }),
  validateConfigAssets: defineOperation({
    id: "validateConfigAssets",
    method: "POST",
    path: "/api/admin/config/validate",
    summary: "Check a bundle of agents and skills without applying it",
    tag: "Config Assets",
    auth: "principal",
    scope: "config_assets:release",
    requires: ["assets.release"],
    effect: "reading",
    body: configAssetBundleSchema,
    response: json(validateConfigAssetsResponseSchema),
    errors: [],
    rateClass: "read"
  })
} as const;
