import { listQuerySchema } from "../shared";
import { z } from "zod";
import {
  cancelRunRequestSchema,
  cancelRunResponseSchema,
  conversationListItemSchema,
  conversationResourceListItemSchema,
  conversationSchema,
  conversationThreadSnapshotSchema,
  createConversationRequestSchema,
  createConversationRunRequestSchema,
  messageSchema,
  moveConversationRequestSchema,
  renameConversationRequestSchema,
  runCommandRequestSchema,
  runCommandResponseSchema,
  runObservationSchema,
  startConversationRunRequestSchema,
  startConversationRunResponseSchema,
  structuredDataResourceResponseSchema
} from "../conversations";
import { defineOperation, json, page, sse } from "./define-operation";

export const conversationOperations = {
  "conversations.list": defineOperation({
    id: "conversations.list",
    method: "GET",
    path: "/api/v1/conversations",
    summary: "List the caller's conversations in a workspace",
    tag: "Conversations",
    auth: "user",
    scope: "conversation:read",
    requires: [],
    effect: "reading",
    query: listQuerySchema.extend({ collaborationWorkspaceId: z.string().optional() }),
    response: page(conversationListItemSchema, ["updatedAt", "id"], true),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  "conversations.create": defineOperation({
    id: "conversations.create",
    method: "POST",
    path: "/api/v1/conversations",
    summary: "Create an empty conversation",
    tag: "Conversations",
    auth: "user",
    scope: "conversation:write",
    requires: [],
    effect: "changing",
    body: createConversationRequestSchema,
    response: json(conversationSchema),
    errors: ["NOT_FOUND"],
    rateClass: "write"
  }),
  "conversations.rename": defineOperation({
    id: "conversations.rename",
    method: "PATCH",
    path: "/api/v1/conversations/:conversationId/title",
    summary: "Rename a conversation",
    tag: "Conversations",
    auth: "user",
    scope: "conversation:write",
    requires: [],
    effect: "changing",
    body: renameConversationRequestSchema,
    response: json(conversationSchema),
    errors: ["NOT_FOUND"],
    rateClass: "write"
  }),
  "conversations.move": defineOperation({
    id: "conversations.move",
    method: "POST",
    path: "/api/v1/conversations/:conversationId/move",
    summary: "Move a conversation to another workspace or visibility",
    tag: "Conversations",
    auth: "user",
    scope: "conversation:write",
    requires: [],
    effect: "changing",
    body: moveConversationRequestSchema,
    response: json(conversationSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  "conversations.thread.get": defineOperation({
    id: "conversations.thread.get",
    method: "GET",
    path: "/api/v1/conversations/:conversationId/thread",
    summary: "Read a conversation with its messages and active run",
    tag: "Conversations",
    auth: "user",
    scope: "conversation:read",
    requires: [],
    effect: "reading",
    response: json(conversationThreadSnapshotSchema),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  "conversations.messages.list": defineOperation({
    id: "conversations.messages.list",
    method: "GET",
    path: "/api/v1/conversations/:conversationId/messages",
    summary: "List the messages of a conversation",
    tag: "Conversations",
    auth: "user",
    scope: "conversation:read",
    requires: [],
    effect: "reading",
    query: listQuerySchema,
    response: page(messageSchema, ["createdAt", "id"], false),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  "conversations.resources.list": defineOperation({
    id: "conversations.resources.list",
    method: "GET",
    path: "/api/v1/conversations/:conversationId/resources",
    summary: "List the files and data a conversation produced",
    tag: "Conversations",
    auth: "user",
    scope: "conversation:read",
    requires: [],
    effect: "reading",
    query: listQuerySchema,
    response: page(conversationResourceListItemSchema, ["updatedAt", "resourceId"], true),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  "conversations.structured_data.get": defineOperation({
    id: "conversations.structured_data.get",
    method: "GET",
    path: "/api/v1/conversations/:conversationId/structured-data/:structuredDataResourceId",
    summary: "Read one structured data resource of a conversation",
    tag: "Conversations",
    auth: "user",
    scope: "conversation:read",
    requires: [],
    effect: "reading",
    response: json(structuredDataResourceResponseSchema),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  "conversations.runs.cancel": defineOperation({
    id: "conversations.runs.cancel",
    method: "POST",
    path: "/api/v1/conversations/:conversationId/runs/:runId/cancel",
    summary: "Cancel an agent run",
    tag: "Conversations",
    auth: "user",
    scope: "run:cancel",
    requires: [],
    effect: "changing",
    body: cancelRunRequestSchema,
    response: json(cancelRunResponseSchema),
    errors: ["NOT_FOUND"],
    rateClass: "write"
  }),
  "conversations.runs.start": defineOperation({
    id: "conversations.runs.start",
    method: "POST",
    path: "/api/v1/conversations/:conversationId/runs",
    summary: "Send a message and start an agent run",
    tag: "Conversations",
    auth: "user",
    scope: "conversation:write",
    requires: [],
    effect: "changing",
    body: startConversationRunRequestSchema,
    response: json(startConversationRunResponseSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  "conversations.runs.create": defineOperation({
    id: "conversations.runs.create",
    method: "POST",
    path: "/api/v1/conversations/runs",
    summary: "Create a conversation and start its first agent run",
    tag: "Conversations",
    auth: "user",
    scope: "conversation:write",
    requires: [],
    effect: "changing",
    body: createConversationRunRequestSchema,
    response: json(startConversationRunResponseSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  "conversations.runs.observe": defineOperation({
    id: "conversations.runs.observe",
    method: "GET",
    path: "/api/v1/conversations/:conversationId/runs/:runId/events",
    summary: "Follow the events of an agent run",
    tag: "Conversations",
    auth: "user",
    scope: "run:observe",
    requires: [],
    effect: "reading",
    query: z.object({ after: z.string().optional() }),
    response: sse(runObservationSchema),
    errors: ["NOT_FOUND"],
    rateClass: "read"
  }),
  "conversations.runs.command": defineOperation({
    id: "conversations.runs.command",
    method: "POST",
    path: "/api/v1/conversations/:conversationId/runs/:runId/commands",
    summary: "Continue a waiting agent run or decide its tool permission",
    tag: "Conversations",
    auth: "user",
    scope: "run:command",
    requires: [],
    effect: "changing",
    body: runCommandRequestSchema,
    response: json(runCommandResponseSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  }),
  "conversations.delete": defineOperation({
    id: "conversations.delete",
    method: "DELETE",
    path: "/api/v1/conversations/:conversationId",
    summary: "Delete a conversation",
    tag: "Conversations",
    auth: "user",
    scope: "conversation:write",
    requires: [],
    effect: "changing",
    response: json(conversationSchema),
    errors: ["NOT_FOUND", "CONFLICT"],
    rateClass: "write"
  })
} as const;
